'я сделал':
  - "%username% отлично, но придется переделать"
'предлагаю':
  - "%username% принял во внимание но пока нет"
'я перепутал|я ошибся|я забыл|не понимаю':
  - сраный позор!
  - бля если так тупо никто не понимает проекта может кто-то не на своем месте?
'внутренн(ем|ий) аукционe?':
  - засуньте себе куда-нить внутренний аукцион
'раньше было':
  - ну было и было
'как (спарсить|вычислить)':
  - давай товарищ программист, научу тебя программировать, хули мне осталось"
'успешно пройден':
  - ай е
'подстраивались под нас':
  - нахуй мне отдел разработки если я должен ждать что кто-то там под чет подстроится
  - :) бляяяяя просто ад, господи дай мне это развидеть)
'ужасная логика':
  - "%username% ужасная логика с которой ты читаешь API чужие"
'[)]{5}|ахаха':
  - "%username% че ты ржешь интегратор года"
'таблицу.*джойнить':
  - "%username% ну ахуеть теперь"
'просто мне кажется':
  - "%username% ты наверное не понял"
'может.*кофе':
  - только тяжелые наркотики!
'релиз':
  - все хуйня давай по новой
'(^| )бот($| )':
  - "%username% сам ты бот, пидор"
